TicketingSystem/TicketingSystem/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketingSystem.Models
{
    public class Ticket
    {
        public int Id { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }

        public DateTime DateCreated { get; set; }

        public TicketStatusType TicketStatus { get; set; }

        public int UserId { get; set; }

        public User User { get; set; }
    }
}

TicketingSystem/TicketingSystem/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketingSystem.Services.Interfaces;
using TicketingSystem.ViewModels;

namespace TicketingSystem.Controllers
{
    public class CommentsController : Controller
    {
        private ICommentsService _commentsService;
        public CommentsController(ICommentsService commentsService)
        {
            _commentsService = commentsService;
        }

        [HttpPost]
        public IActionResult Add(CommentCreateModel commentCreateModel)
        {

            var userId = int.Parse(User.FindFirst("Id").Value);

            var response = _commentsService.Add(commentCreateModel.Comment, commentCreateModel.TicketId , userId);

            if (response.IsSuccessful)
            {
                return RedirectToAction("Details", "Ticket", new { id = commentCreateModel.TicketId });
            }
            else
            {
                return RedirectToAction("ActionNonSuccessful", "Info", new { Message = response.Message });
            }

            
        }
    }
}

TicketingSystem/TicketingSystem/Controllers/TicketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketingSystem.Mappings;
using TicketingSystem.Services.Interfaces;
using TicketingSystem.ViewModels;

namespace TicketingSystem.Controllers
{
    public class TicketController : Controller
    {
        private ITicketsService _ticketsService;
        public TicketController(ITicketsService ticketsService)
        {
            _ticketsService = ticketsService;
        }

        [Authorize]
        public IActionResult Overview(string adminFilterOption)
        {

            if (bool.Parse(User.FindFirst("IsAdmin").Value))
            {
                if (adminFilterOption == null)
                {
                    var tickets = _ticketsService.GetAll();
                    var viewTickets = tickets.Select(x => x.ToOverviewModel()).ToList();
                    return View(viewTickets);
                }
                else
                {
                    var tickets = _ticketsService.GetTicketsWithAdminFilter(adminFilterOption);
                    var viewTickets = tickets.Select(x => x.ToOverviewModel()).ToList();
                    return View(viewTickets);
                }
            }
            else
            {
                var userId = int.Parse(User.FindFirst("Id").Value);
                var tickets = _ticketsService.GetAllForCurrentUser(userId);
                var viewTickets = tickets.Select(x => x.ToOverviewModel()).ToList();
                return View(viewTickets);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TicketCreateModel ticketCreateModel)
        {
            if (ModelState.IsValid)
            {
                var domainModel = ticketCreateModel.ToModel();
                domainModel.UserId = int.Parse(User.FindFirst("Id").Value);
                var response = _ticketsService.CreateTicket(domainModel);

                return RedirectToAction("Overview", "Ticket");
            }
            else
            {
                return View(ticketCreateModel);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var ticket = _ticketsService.GetById(id);
            var ticketDetailsModel = ticket.ToDetailsModel();

            return View(ticketDetailsModel);
        }

        [HttpPost]
        public IActionResult ChangeStatus(string ticketStatus, int ticketId)
        {
            if (ticketStatus == "processing")
            {
                var response = _ticketsService.ChangeStatus(ticketStatus, ticketId);
                return RedirectToAction("Details", "Ticket", new { id = ticketId } );
                
            }
            else
            {
                var response =_ticketsService.ChangeStatus(ticketStatus, ticketId);
                return RedirectToAction("Details", "Ticket" , new { id = ticketId });
            }

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var response = _ticketsService.Delete(id);

            return RedirectToAction("Overview", "Ticket");
        }
    }
}

TicketingSystem/TicketingSystem/Views/Ticket/ChangeStatus.cshtml
<h1>    Change Status VIEW</h1>

TicketingSystem/TicketingSystem/Views/Ticket/Create.cshtml
@model TicketingSystem.ViewModels.TicketCreateModel

<form asp-controller="Ticket" asp-action="Create" method="post">
    <div class="form-group">
        <label class="control-label" asp-for="Title">Title</label>
        <input type="text" asp-for="Title" class="form-control" required />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label" asp-for="Description">Description</label>
        <textarea type="text" asp-for="Description" class="form-control" cols="20" rows="5" required></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div> <div class="form-group">
        <input type="submit" value="Create" class="btn btn-success" />
    </div>
</form>

<h1>    THIS IS CREATE</h1>

TicketingSystem/TicketingSystem/Views/Ticket/Details.cshtml
@model TicketingSystem.ViewModels.TicketDetailsModel


<div class="row">

    <div class=" col-10 offset-1" style="text-align:center">

        <div class="card" style="width: 80vw;">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><h1>  @Model.Title  </h1></li>
                <li class="list-group-item"> <b> Status:</b> @Model.TicketStatus</li>
                <li class="list-group-item"> <b> Description:</b> @Model.Description</li>
                <li class="list-group-item"><p> <b>Date created:</b> @Model.DateCreated</p></li>

                <li class="list-group-item">

                    @if (!User.HasClaim("IsAdmin", "True") && @Model.TicketStatus != TicketStatusType.Done || (User.HasClaim("IsAdmin", "True")))
                    {
                        <b>Change status to:</b>
                    }


                    @if (User.HasClaim("IsAdmin", "True") && @Model.TicketStatus != TicketStatusType.Processing)
                    {
                        <form asp-controller="Ticket" asp-action="ChangeStatus" asp-route-ticketStatus="processing" method="post" class="m-2">
                            <input type="text" name="ticketId" value="@Model.Id" hidden />
                            <button type="submit" class="btn btn-warning" onclick="return confirm('Are you sure?')">Processing</button>
                        </form>
                    }

                    @if (@Model.TicketStatus != TicketStatusType.Done)
                    {
                        <form asp-controller="Ticket" asp-action="ChangeStatus" asp-route-ticketStatus="done" method="post" class="m-2">
                            <input type="text" name="ticketId" value="@Model.Id" hidden />
                            <button type="submit" class="btn btn-success" onclick="return confirm('Are you sure?')">Done</button>
                        </form>
                    }
                </li>
            </ul>
        </div>



       
    </div>

    <div class="card col-10 offset-1" style="width: 60vw; margin-top:1rem">
        @if (User.Identity.IsAuthenticated)
         {
            <form asp-controller="Comments" asp-action="Add" method="post">
                <input type="text" name="ticketId" value="@Model.Id" hidden />
                <div class="form-group">
                    <textarea type="text" id="comment" name="comment" class="form-control" cols="20" rows="5" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
         }

        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateCreated))
         {
            <div class="comment m-2" style="border:1px solid black; border-radius: 0.5rem">
                <p>@comment.Message</p>
                @if (comment.IsAdmin)
                {
                    <p> <b>- A D M I N -:</b> @comment.Username</p>
                }
                else
                {
                    <p> <b>User:</b> @comment.Username</p>
                }
                <p> <b>Date created:</b> @comment.DateCreated</p>
            </div>
         }
    </div>

</div>

TicketingSystem/TicketingSystem/Views/Ticket/Overview.cshtml
@model List<TicketingSystem.ViewModels.TicketOverviewModel>


@if (!User.HasClaim("IsAdmin", "True"))
{
    <div class="row justify-content-start m-4">
        <a class="btn btn-success" href="/Ticket/Create">Create new Ticket</a>

    </div>
}
else
{
    <h1>Admin console</h1>

        <table class="table row col-8 offset-2">
             <thead>
                <tr>
                    <th scope="col">Order by:</th>
                    <th scope="col">
                        <a asp-controller="Ticket" asp-action="Overview" asp-route-adminFilterOption="pending" class="btn btn-info">Pending</a>
                    </th>
                    <th scope="col">
                        <a asp-controller ="Ticket" asp-action="Overview" asp-route-adminFilterOption="inProcess" class="btn btn-warning">In Process</a>
                    </th>
                    <th scope="col">
                        <a asp-controller ="Ticket" asp-action="Overview" asp-route-adminFilterOption="done" class="btn btn-success">Done</a>
                    </th>
                 </tr>
            </thead>
        </table>
 }


        @if (Model.Count == 0)
        {
            <h3>There are no Tickets</h3>
        }
        else
        {
            <div class="row col-8 offset-2">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th> Id</th>
                        <th> Title</th>
                        <th> Status</th>
                        <th> Date Created</th>
                        <th> Manage</th>
                    </tr>
                    @foreach (var ticket in Model)
                    {
                        <tr>
                            <td>@ticket.Id</td>
                            <td>@ticket.Title</td>
                            <td>@ticket.TicketStatus</td>
                            <td>@ticket.DateCreated</td>
                            <td style="text-align:center">
                                <a href="/Ticket/Details/@ticket.Id" class="btn btn-info">Details</a>

                                @if (!User.HasClaim("IsAdmin", "True"))
                                {
                                    <a href="/Ticket/Delete/@ticket.Id" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</a>
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>

        }